#ifndef __CONSOLELOGIC_INCLUDED__
#define __CONSOLELOGIC_INCLUDED__

#include <console/ConsoleBase.h>

typedef struct _ATTR_CHAR_PAIR
{
	UCHAR Attr;
	UCHAR Char;
}ATTR_CHAR_PAIR,*PATTR_CHAR_PAIR;

typedef struct _CONSOLE_LOGIC
{
	ULONG Columns;
	ULONG Rows;
	ULONG CursorX;
	ULONG CursorY;
	UCHAR CursorShow;
	UCHAR CursorInsert;
	ULONG MousePointerX;
	ULONG MousePointerY;
	UCHAR MousePointerShow;
	PATTR_CHAR_PAIR AttrCharPairGrid;
	PUCHAR ChangedAttrCharPairs;
	UCHAR CursorChanged;
	UCHAR MousePointerChanged;
}CONSOLE_LOGIC,*PCONSOLE_LOGIC;

int CONSOLE_LOGIC_Initialize(PCONSOLE_LOGIC Console, ULONG Columns, ULONG Rows);
int CONSOLE_LOGIC_Finalize(PCONSOLE_LOGIC Console);
ULONG CONSOLE_LOGIC_GetColumns(PCONSOLE_LOGIC Console);
ULONG CONSOLE_LOGIC_GetRows(PCONSOLE_LOGIC Console);
int CONSOLE_LOGIC_PutAttrCharPairXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, UCHAR Attr, UCHAR Char);
int CONSOLE_LOGIC_GetAttrCharPairXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, PUCHAR pAttr, PUCHAR pChar);
int CONSOLE_LOGIC_PutCharXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, UCHAR Char);
int CONSOLE_LOGIC_GetCharXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, PUCHAR pChar);
int CONSOLE_LOGIC_PutAttrXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, UCHAR Attr);
int CONSOLE_LOGIC_GetAttrXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, PUCHAR pAttr);
int CONSOLE_LOGIC_PutBackAttrXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, UCHAR BackAttr);
int CONSOLE_LOGIC_GetBackAttrXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, PUCHAR pBackAttr);
int CONSOLE_LOGIC_PutTextAttrXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, UCHAR TextAttr);
int CONSOLE_LOGIC_GetTextAttrXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y, PUCHAR pTextAttr);
int CONSOLE_LOGIC_GetCursorXY(PCONSOLE_LOGIC Console, PULONG pX, PULONG pY);
int CONSOLE_LOGIC_ShowCursor(PCONSOLE_LOGIC Console, UCHAR Show);
int CONSOLE_LOGIC_IsCursorVisible(PCONSOLE_LOGIC Console);
int CONSOLE_LOGIC_PutCursorXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y);
int CONSOLE_LOGIC_PutCursorInsert(PCONSOLE_LOGIC Console, UCHAR Insert);
int CONSOLE_LOGIC_IsCursorInsert(PCONSOLE_LOGIC Console);
int CONSOLE_LOGIC_GetMousePointerXY(PCONSOLE_LOGIC Console, PULONG pX, PULONG pY);
int CONSOLE_LOGIC_ShowMousePointer(PCONSOLE_LOGIC Console, UCHAR Show);
int CONSOLE_LOGIC_IsMousePointerVisible(PCONSOLE_LOGIC Console);
int CONSOLE_LOGIC_PutMousePointerXY(PCONSOLE_LOGIC Console, ULONG X, ULONG Y);
int CONSOLE_LOGIC_ResetChanges(PCONSOLE_LOGIC Console, UCHAR FalseTrue);
int CONSOLE_LOGIC_GetNextChangedSlot(PCONSOLE_LOGIC Console, PULONG pHandle, PULONG pX, PULONG pY);
int CONSOLE_LOGIC_CursorChanged(PCONSOLE_LOGIC Console);
int CONSOLE_LOGIC_MousePointerChanged(PCONSOLE_LOGIC Console);

#endif//__CONSOLELOGIC_INCLUDED__
